---
title: 'Lecture note: 2017 Advanced biological statics'
author: Youngjun Na
output: github_document
---
# 1. 일단 따라해봅시다
## 1.1. 정의하기
```{r}
a<-10 #a는 10입니다.
b<-5 #b는 5입니다.
c<-"animal" #c는 animal입니다.
```
- 주의: 변수 이름은 문자로 시작해야합니다.  


## 1.2. 출력하기
```{r}
a
b
c
```


## 1.3. 사칙연산
```{r}
a+b #더하기
a-b #빼기
a/b #나누기
a*b #곱하기
a^2 #제곱
sqrt(a^2) #루트
```

## 1.4. 논리
```{r}
a==b #a는 b와 같다.
a!=b #a는 b와 같지 않다.
a>b #a는 b보다 크다.
a<b #a는 b보다 작다.
```

## 1.5. 데이터셋
```{r}
a<-1:10

a
```

```{r}

b<-c(1,2,3,4,5,10)

b
```

```{r}
c<-c("Konkuk","University")

c
```
- c는 '합치다'라는 뜻의 'combine'의 약자입니다.  

```{r}
example<-data.frame(name=c("철수","영희","건이"), sex=c("Male","Female","Male"),age=c(29,40,33), height=c(175,163,168))

example
```

```{r}
x<-example$height #example 데이터 중 height 데이터만 추출
x
```

```{r}
example[2,3]
example[3,3]
example[,3]
example[1,]
example[-1,]
example[c(2,3),]
```


## 1.6. 기본 통계
```{r}
sum(x) #합계
mean(x) #평균
median(x) #중간값
var(x) #분산
sd(x) #표준편차
max(x) #최대값
min(x) #최소값
range(x) #범위
```



# 2. 기초 R 문법
## 2.1. Working directory 확인  
```{r}
getwd()
```

## 2.2. Working directory 설정
```{r eval=FALSE}
setwd(C:/Users/Youngjun/Google Drive/Lecture/2017/건국대학교/생물통계학특론(농축대학원))
```

## 2.3. Working directory 안에 있는 파일 확인
```{r}
dir()
```

## 2.4. 패키지 인스톨
```{r eval=FALSE}
install.packages("dplyr")
install.packages("ggplot2")
install.packages("readxl")
```

## 2.5. 패키지 업데이트
```{r eval=FALSE}
update.packages(ask=FALSE)
```


## 2.6. 패키지 로딩
```{r eval=FALSE}
library(dplyr)
library(ggplot2)
```

## 2.7. 파일 읽기
```{r eval=FALSE}
read.csv("dataframe.csv")
readxl::read_excel("dataframe.xlsx")
```

## 2.8. 파일 쓰기
```{r eval=FALSE}
write.csv(example, "test.txt", row.names=FALSE)
```





